Motd:
  Enabled: true
  First_Line_Static: true
  First_Line_Text: "My server"
  Messages:
    - "Have a great time!"
    - "Check out our website! http://example.com"
    - "Join the discord! http://discord.gg/example"
    - "Join now!"
    - "Now supporting the latest mc version!"
Afk:
  Stop_Counting_Playtime: 60
  Kick_Time_In_Seconds: 3600
Chat:
  Chat_Enabled: true
  No_Permissions_Chat_Color: false
  Message_Format: "%prefix%player%suffix: %message"
Prefix: "&8[&9&lServer&8] &7"
Version: 1